# Generated by Django 2.2.11 on 2020-04-05 08:39

import core.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descripción corta de que estás necesitando', max_length=200, verbose_name='Título del pedido')),
                ('message', models.TextField(blank=True, help_text='Acá podes contar detalladamente lo que necesitas', max_length=2000, null=True, verbose_name='Descripción del pedido')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono de contacto')),
                ('address', models.CharField(blank=True, help_text='Es opcional pero puede ayudar a quien quiera ayudarte saber la direccion, ciudad, barrio, referencias, o como llegar', max_length=400, null=True, verbose_name='Dirección')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Seleccioná tu ubicación para que la gente pueda encontrarte, si no querés marcar tu casa una buena opción puede ser la comisaria más cercana o algún otro sitio público cercano', srid=4326, verbose_name='Ubicación')),
                ('picture', models.ImageField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu pedido, es opcional pero puede ayudar a que la gente entienda mejor tu situación', null=True, upload_to=core.utils.rename_img, verbose_name='Foto')),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Agregado')),
                ('votsi', models.IntegerField(blank=True, default=0)),
                ('votno', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
