# Generated by Django 2.2.11 on 2020-04-07 05:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Agregado'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Seleccioná tu ubicación para que la gente pueda encontrarte, si no querés marcar tu casa una buena opción puede ser la comisaría más cercana o algún otro sitio público cercano.            <br>Si tenés problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">mirá esta ayuda</a>', srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podes contar detalladamente lo que necesitas, <b>cuanto mejor cuentes tu situación es más probable que te quieran ayudar</b>', max_length=2000, null=True, verbose_name='Descripción del pedido'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='title',
            field=models.CharField(db_index=True, help_text='Descripción corta de que estás necesitando', max_length=200, verbose_name='Título del pedido'),
        ),
    ]
