# Generated by Django 2.2.11 on 2020-04-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='city',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='city_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
    ]
