# Generated by Django 2.2.12 on 2020-04-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_addcity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='votno',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='helprequest',
            old_name='votsi',
            new_name='upvotes',
        ),
    ]
