# Generated by Django 2.2.12 on 2020-04-08 13:55

from django.db import migrations, models
from core.models import HelpRequest


def resave_all_requests(auth, schema):
    for obj in HelpRequest.objects.all():
        obj.save()
    print('\n Unvalid locations found: %d' % HelpRequest.objects.filter(loc_validated=False).count())

def revert_save(auth, schema):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_addcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='country',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='country_code',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='loc_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(resave_all_requests, revert_save)
    ]
