# Generated by Django 2.2.11 on 2020-04-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_redefine_requestvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(help_text='Nombre del estado', max_length=40, verbose_name='Nombre del estado')),
                ('code', models.CharField(db_index=True, help_text='Código del estado', max_length=10, primary_key=True, serialize=False, verbose_name='Código del estado')),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='address',
            field=models.CharField(help_text='Para ayudar a quien quiera ayudarte saber la dirección, ciudad, barrio, referencias, o como llegar', max_length=400, null=True, verbose_name='Dirección'),
        ),
    ]
