# Generated by Django 2.2.12 on 2020-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200409_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(help_text='Nombre del estado', max_length=40, verbose_name='Nombre del estado')),
                ('code', models.CharField(db_index=True, help_text='Código del estado', max_length=10, primary_key=True, serialize=False, verbose_name='Código del estado')),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
    ]
