# Generated by Django 2.2.12 on 2020-04-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentAskedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=3, verbose_name='orden')),
                ('question', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('answer', models.TextField(max_length=1000, verbose_name='Respuesta')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_faq',
                'ordering': ['order'],
            },
        ),
    ]
