# Generated by Django 2.2.12 on 2020-04-11 17:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('core', '0006_frequentaskedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Podes escribir todo lo que necesitas, Ej. leche, harina, arroz, pañal', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Escribe tus necesidades'),
        ),
        migrations.AlterUniqueTogether(
            name='helprequest',
            unique_together={('title', 'name', 'phone')},
        ),
    ]
