# Generated by Django 2.2.12 on 2020-04-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_frequentaskedquestion'),
        ('core', '0006_helprequest_search_vector'),
    ]

    operations = [
    ]
