# Generated by Django 2.2.12 on 2020-04-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20200410_2300'),
        ('core', '0007_addusercookies'),
    ]

    operations = [
    ]
