# Generated by Django 2.2.12 on 2020-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_helprequest_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='city_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_code',
            field=models.CharField(blank=True, help_text='Código de Ciudad por Defecto del Usuario', max_length=50, null=True, verbose_name='Código Ciudad'),
        ),
    ]
