# Generated by Django 2.2.12 on 2020-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_helprequest_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='push_notification_token',
            field=models.CharField(blank=True, help_text='Token de Notificación para envíos tipo PUSH', max_length=128, null=True, verbose_name='Token de Notificación'),
        ),
    ]
