# Generated by Django 2.2.12 on 2020-04-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20200411_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='helprequest',
            unique_together=set(),
        ),
    ]
