# Generated by Django 2.2.12 on 2020-04-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200411_2203'),
        ('core', '0009_device_push_notification_token'),
    ]

    operations = [
    ]
