# Generated by Django 2.2.11 on 2020-04-16 09:56

from django.db import migrations, models


def populate_cats(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Category.objects.create(name="Víveres", code="viveres", color="#00d1b2")
    Category.objects.create(name="Medicamentos", code="medicamentos", color="#ff3860")
    Category.objects.create(name="Art. de Limpieza", code="limpieza", color="#ffdd57")
    Category.objects.create(name="Art. de Bebés", code="bebes", color="#209cee")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200414_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(populate_cats, migrations.RunPython.noop),
    ]
