# Generated by Django 2.2.11 on 2020-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.Category'),
        ),
    ]
