# Generated by Django 2.2.11 on 2020-04-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_city_to_50_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalhelprequest',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
