# Generated by Django 2.2.11 on 2020-04-12 05:36

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de contacto')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('address', models.CharField(help_text='Dirección, ciudad, barrio, referencias, o cómo llegar', max_length=400, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='', editable=False, max_length=30)),
                ('city_code', models.CharField(blank=True, default='', editable=False, max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Agregado')),
            ],
            options={
                'verbose_name': 'Centro de Donación',
                'verbose_name_plural': 'Centros de Donación',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Organización')),
            ],
            options={
                'verbose_name': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono de contacto')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('department', models.PositiveSmallIntegerField(choices=[(0, 'Asuncion'), (1, 'Alto Paraguay'), (2, 'Alto Paraná'), (3, 'Amambay'), (4, 'Boquerón'), (5, 'Caaguazú'), (6, 'Caazapá'), (7, 'Canindeyú'), (8, 'Central'), (9, 'Concepción'), (10, 'Cordillera'), (11, 'Guairá'), (12, 'Itapúa'), (13, 'Misiones'), (14, 'Ñeembucú'), (15, 'Paraguarí'), (16, 'Presidente Hayes'), (17, 'San Pedro')])),
                ('address', models.CharField(help_text='Dirección, ciudad, barrio, referencias, o cómo llegar', max_length=400, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='', editable=False, max_length=30)),
                ('city_code', models.CharField(blank=True, default='', editable=False, max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Agregado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voluntario',
            },
        ),
    ]
